export { default as Header } from './header/header'
export { default as Footer } from './footer/footer'
export { default as Home } from './home/home'
export { default as About } from './about/about'
export { default as Contact} from './contact/contact'
export { default as Blog} from './blog/blog'
export { default as BlogDetail} from './blog/BlogItem/BlogDetail'
export { default as NotFound} from './404/NotFound'
export { default as News} from './news/news'
export { default as NewsHead} from './news/newsHead'
export { default as MiniCard} from './cards/miniCard'
export { default as MiddleHomeCards} from './cards/middleHomeCards'
export { default as CategoryCard} from './cards/categoryCard'
export { default as AllVideos} from './videos/AllVideos'
export { default as ShortNewsPage} from './shortNewsPage/shortNewsPage'
export { default as ShortNewsHead} from './shortNewsPage/ShortNewsHead'